/* ============================================================
   books-data.js — Derradj Shop | بيانات قسم الكتب
   catalogId يجب أن يتطابق مع SHOP_CATALOG في cart.js
   ============================================================ */

window.BOOKS_DATA = (function () {
  'use strict';

  return [
    {
      id: 2, title: 'العادات السبع للناس الأكثر فعالية', titleEn: 'The 7 Habits of Highly Effective People',
      author: 'ستيفن آر. كوفي', translator: 'هشام عبد الله', year: 1989,
      category: 'تطوير الذات', price: 1400, image: '7-habits/main.png', url: '7-habits/',
      available: true,
      description: 'سبعة مبادئ لبناء الشخصية الفعّالة والنجاح في الحياة الشخصية والمهنية والاجتماعية، مبنية على قيم راسخة ونظرة عميقة للإنسان.',
    },
    {
      id: 3, title: 'العادات الذرية', titleEn: 'Atomic Habits',
      author: 'جيمس كلير', translator: 'محمد فتحي خضر', year: 2018,
      category: 'تطوير الذات', price: 950, image: 'atomic-habits/main.png', url: 'atomic-habits/',
      available: true,
      description: 'استراتيجيات علمية وعملية لبناء عادات إيجابية والتخلص من العادات السلبية عبر تغييرات صغيرة تتراكم لتُحدث نتائج استثنائية.',
    },
    {
      id: 4, title: 'قاعدة الـ 333', titleEn: 'Rule 3-3-3',
      author: 'شهاب الهاشمي', translator: null, year: 2024,
      category: 'تطوير الذات', price: 1350, image: 'rule-333/main.png', url: 'rule-333/',
      available: true,
      description: 'خلاصات وأفكار قيّمة في العلاقات العامة وصناعة المحتوى الرقمي وبناء الحضور الشخصي عبر قاعدة مبسّطة وفعّالة.',
    },
    {
      id: 5, title: 'الأثر المذهل للعادات البسيطة', titleEn: 'Small Habits Revolution',
      author: 'ديمون زهاريادس', translator: 'مروة هاشم', year: 2016,
      category: 'تطوير الذات', price: 1200, image: 'small-habits-revolution/main.png', url: 'small-habits-revolution/',
      available: true,
      description: 'دليل عملي لاكتساب عادات مستدامة تدريجياً بدلاً من التغيير الجذري المفاجئ، مع التركيز على الاتساق والمثابرة اليومية.',
    },
    {
      id: 6, title: 'متعة عدم الكمال', titleEn: 'The Joy of Imperfection',
      author: 'ديمون زهاريادس', translator: null, year: 2017,
      category: 'تطوير الذات', price: 900, image: 'joy-of-imperfection/main.png', url: 'joy-of-imperfection/',
      available: true,
      description: 'دليل شامل للتغلب على وسواس الكمالية وإسكات الناقد الداخلي، واكتشاف أن النقص الإنساني هو أصل الجمال والتطور.',
    },
    {
      id: 7, title: 'الشجاعة تنادي', titleEn: 'Courage Is Calling',
      author: 'ريان هوليداي', translator: 'محمد أقديم', year: 2021,
      category: 'الفلسفة والفكر', price: 1300, image: 'courage-is-calling/main.png', url: 'courage-is-calling/',
      available: true,
      description: 'عبر قصص تاريخية ملهمة يستكشف الكاتب معنى الشجاعة الحقيقية وكيف نتغلب على الخوف الذي يمنعنا من تحقيق أهدافنا.',
    },
    {
      id: 8, title: 'قوة الآن', titleEn: 'The Power of Now',
      author: 'إيكهارت تول', translator: 'مينا كمال', year: 1997,
      category: 'الفلسفة والفكر', price: 1100, image: 'power-of-now/main.png', url: 'power-of-now/',
      available: true,
      description: 'دليل روحي عميق للعيش في اللحظة الراهنة والتحرر من قيود الماضي وقلق المستقبل لتحقيق السلام الداخلي الحقيقي.',
    },
    {
      id: 9, title: 'بروباغندا', titleEn: 'Propaganda',
      author: 'إدوارد بيرنايز', translator: 'يحيى العريضي', year: 1928,
      category: 'علم النفس والمجتمع', price: 1100, image: 'propaganda/main.png', url: 'propaganda/',
      available: true,
      description: 'الكتاب الأصل في علم العلاقات العامة يكشف آليات التأثير في الجماهير والرأي العام وكيف يمكن توجيه سلوك الناس على نطاق واسع.',
    },
    {
      id: 10, title: 'فوضى الإدارة', titleEn: 'Management Mess to Leadership Success',
      author: 'سكوت جيفري ميلر', translator: null, year: 2019,
      category: 'الإدارة والأعمال', price: 1600, image: 'management-mess/main.png', url: 'management-mess/',
      available: true,
      description: 'ثلاثون تحدياً حقيقياً يواجهها القادة في مسيرتهم المهنية، مع حلول عملية وتجارب واقعية للتغلب عليها.',
    },
    {
      id: 11, title: 'السعادة الحقيقية والسعادة الزائفة', titleEn: 'The Myths of Happiness',
      author: 'سونيا ليوبوميرسكي', translator: 'سمر حجازي', year: 2013,
      category: 'علم النفس والمجتمع', price: 1600, image: 'myths-of-happiness/main.png', url: 'myths-of-happiness/',
      available: true,
      description: 'تدحض الباحثة النفسية الأساطير الشائعة حول مصادر السعادة وتقدم بدائل علمية مستندة إلى أبحاث موثقة لبناء سعادة حقيقية ومستدامة.',
    },
    {
      id: 12, title: 'مسارات السعادة', titleEn: 'Happy Ever After',
      author: 'بول دولان', translator: null, year: 2019,
      category: 'علم النفس والمجتمع', price: 1300, image: 'happy-ever-after/main.png', url: 'happy-ever-after/',
      available: true,
      description: 'اكتشاف معنى السعادة الحقيقية بتجاوز القوالب النمطية والتوقعات الاجتماعية، بقلم أحد أبرز الباحثين في علم الاقتصاد السلوكي.',
    },
    {
      id: 13, title: 'في عالم الأشباح الجائعة', titleEn: 'In the Realm of Hungry Ghosts',
      author: 'غابور ماتيه', translator: null, year: 2008,
      category: 'علم النفس والمجتمع', price: 1800, image: 'hungry-ghosts/main.png', url: 'hungry-ghosts/',
      available: true,
      description: 'استكشاف عميق للجذور النفسية والاجتماعية للإدمان والصدمات النفسية وكيفية التعافي منها بأسلوب إنساني وعلمي رائع.',
    },
    {
      id: 14, title: 'تاريخ موجز للزمان', titleEn: 'A Brief History of Time',
      author: 'ستيفن هوكينج', translator: 'د. أدهم السمّان', year: 1988,
      category: 'العلوم والمعرفة', price: 1200, image: 'brief-history-of-time/main.png', url: 'brief-history-of-time/',
      available: true,
      description: 'رحلة علمية مبسّطة ورائعة في أعماق الكون من أصغر الجسيمات إلى أسرار الزمان والمكان والثقوب السوداء وأصل الكون.',
    },
    {
      id: 16, title: 'متعة أن تكون في الثلاثين', titleEn: 'The Joy of Being Thirty',
      author: 'علا ديوب', translator: null, year: 2019,
      category: 'تطوير الذات', price: 950, image: 'joy-of-thirties/main.png', url: 'joy-of-thirties/',
      available: true,
      description: 'مقالات متنوعة وملهمة حول مرحلة الثلاثينيات وما تحمله من نضج وخبرة وتحولات عميقة في الرؤية للذات والعالم.',
    },
    {
      id: 17, title: 'كن مع الشخص الذي يجعلك سعيداً', titleEn: 'Be with the One Who Makes You Happy',
      author: 'مؤلفون مختلفون', translator: null, year: null,
      category: 'العلاقات والحياة', price: 1200, image: 'be-happy-with-someone/main.png', url: 'be-happy-with-someone/',
      available: true,
      description: 'أهمية البيئة الداعمة واختيار الشريك المناسب لبناء حياة مليئة بالسعادة والانسجام والنمو الشخصي المشترك.',
    },
    {
      id: 20, title: 'الذكاء العاطفي', titleEn: 'Emotional Intelligence',
      author: 'دانيال جولمان', translator: 'ليلى الجبالي', year: 1995,
      category: 'علم النفس والمجتمع', price: 1600, image: 'emotional-intelligence/main.png', url: 'emotional-intelligence/',
      available: true,
      description: 'كيف يتفوق الذكاء العاطفي على معدل الذكاء التقليدي في تحقيق النجاح وبناء العلاقات وإدارة المشاعر والتعامل مع التحديات.',
    },
    {
      id: 21, title: 'كيف تبيع أي شيء لأي إنسان', titleEn: 'How to Sell Anything to Anybody',
      author: 'جو جيرارد', translator: null, year: 1977,
      category: 'الإدارة والأعمال', price: 1100, image: 'sell-anything/main.png', url: 'sell-anything/',
      available: true,
      description: 'أسرار المبيعات من أفضل بائع في العالم وفقاً لموسوعة غينيس، مع أساليب عملية وقصص واقعية تُغير طريقة التفكير في البيع.',
    },
    {
      id: 22, title: 'كيف تسوق نفسك', titleEn: 'How to Sell Yourself',
      author: 'جو جيرارد', translator: null, year: 1979,
      category: 'الإدارة والأعمال', price: 1700, image: 'sell-yourself/main.png', url: 'sell-yourself/',
      available: true,
      description: 'من أفضل بائع في العالم وفقاً لغينيس — دليل عملي لتسويق شخصيتك وقدراتك في الحياة والعمل، لأن البيع الأول دائماً هو بيع نفسك.',
    },
    {
      id: 23, title: 'كيف تتقن إتمام الصفقات', titleEn: 'How to Close Every Sale',
      author: 'جو جيرارد', translator: null, year: 1989,
      category: 'الإدارة والأعمال', price: 1500, image: 'mastering-deals/main.png', url: 'mastering-deals/',
      available: true,
      description: 'تقنيات احترافية لإغلاق الصفقات وتحويل كل فرصة إلى نتيجة ناجحة، مستخلصة من تجربة ميدانية حقيقية لأعظم مندوب مبيعات في التاريخ.',
    },
    {
      id: 24, title: 'سيكولوجية المال', titleEn: 'The Psychology of Money',
      author: 'مورجان هاوسل', translator: null, year: 2020,
      category: 'الإدارة والأعمال', price: 1600, image: 'psychology-of-money/main.png', url: 'psychology-of-money/',
      available: true,
      description: 'كيف تؤثر مشاعرنا وتحيزاتنا وسلوكياتنا على قراراتنا المالية أكثر من المعرفة التقنية — درس عميق في علاقة الإنسان بالمال وطريق بناء الثروة الحقيقية.',
    },
    {
      id: 25, title: 'العقل الباطن', titleEn: 'The Subconscious Mind',
      author: 'فيكتور بوشيه', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 950, image: 'subconscious-mind/main.png', url: 'subconscious-mind/',
      available: true,
      description: 'رحلة استكشافية في أعماق العقل الباطن وآلياته الخفية التي تحرك سلوكنا وقراراتنا وعلاقاتنا دون وعي منّا، مع أساليب للتحكم فيها والاستفادة منها.',
    },
    {
      id: 26, title: 'فن اللامبالاة', titleEn: 'The Subtle Art of Not Giving a F*ck',
      author: 'مارك مانسون', translator: null, year: 2016,
      category: 'تطوير الذات', price: 900, image: 'subtle-art/main.png', url: 'subtle-art/',
      available: true,
      description: 'مقاربة استفزازية ومختلفة لحياة أفضل — تعلّم كيف تختار ما تهتم به بعناية، وتتخلى عما لا يستحق طاقتك، لتعيش بحرية وأصالة حقيقية.',
    },
    {
      id: 27, title: 'سيكولوجية الجماهير', titleEn: 'The Crowd',
      author: 'غوستاف لوبون', translator: null, year: 1895,
      category: 'علم النفس والمجتمع', price: 750, image: 'crowd-psychology/main.png', url: 'crowd-psychology/',
      available: true,
      description: 'الكتاب الكلاسيكي الذي أسّس علم نفس الجماهير — يكشف كيف تفكر الحشود وتتصرف بطريقة مختلفة كلياً عن الأفراد، ولماذا يُعدّ من أكثر الكتب تأثيراً في التاريخ.',
    },
    {
      id: 28, title: 'السنن النفسية لتطور الأمم', titleEn: 'The Psychology of Peoples',
      author: 'غوستاف لوبون', translator: null, year: 1894,
      category: 'علم النفس والمجتمع', price: 1300, image: 'psychological-laws/main.png', url: 'psychological-laws/',
      available: true,
      description: 'دراسة معمّقة في الخصائص النفسية للشعوب وكيف تحدد شخصيتها الجماعية مساراتها الحضارية والتاريخية — إسهام فريد في فهم الديناميكيات الاجتماعية للأمم.',
    },
    {
      id: 29, title: 'الآراء والمعتقدات', titleEn: 'The Psychology of Revolution',
      author: 'غوستاف لوبون', translator: null, year: 1912,
      category: 'علم النفس والمجتمع', price: 1550, image: 'opinions-beliefs/main.png', url: 'opinions-beliefs/',
      available: true,
      description: 'كيف تتشكّل الآراء والمعتقدات الجماعية وتنتشر في المجتمعات — تحليل نفسي دقيق لآليات التأثير والإقناع الجماهيري من أبرز علماء النفس الاجتماعي.',
    },
    {
      id: 30, title: 'الذكر العقلاني: الذكورة الإيجابية', titleEn: 'The Rational Male',
      author: 'رولو توماسي', translator: null, year: 2013,
      category: 'تطوير الذات', price: 2100, image: 'rational-male/main.png', url: 'rational-male/',
      available: true,
      description: 'مرجع شامل يستكشف الديناميكيات النفسية للعلاقات بين الجنسين والهوية الذكورية، مقدّماً رؤية عقلانية وموضوعية لفهم الذكورة الإيجابية وبناء الشخصية القوية.',
    },
    {
      id: 31, title: '6 مهارات لتحقيق مبيعات مختلفة مذهلة', titleEn: '6 Skills to Super-Charge Your Sales',
      author: 'ديل ميريل، جينيفر كولوسيمو، سكوت سافاج، راندي إلينج', translator: null, year: null,
      category: 'الإدارة والأعمال', price: 1400, image: '6-sales-skills/main.png', url: '6-sales-skills/',
      available: true,
      description: 'ست مهارات عملية مجرّبة لرفع مستوى أدائك في المبيعات إلى آفاق جديدة — دليل ميداني من خبراء متخصصين لتحقيق نتائج مذهلة في بيئات المبيعات التنافسية.',
    },
    {
      id: 32, title: 'الأثر المذهل للعادات البسيطة', titleEn: 'Small Habits Revolution',
      author: 'ديمون زهاريادس', translator: null, year: 2018,
      category: 'تطوير الذات', price: 1800, image: 'small-habits-effect/main.png', url: 'small-habits-effect/',
      available: true,
      description: 'الطبعة المحدّثة والموسّعة — دليل شامل لاكتساب عادات مستدامة بأساليب علمية مجرّبة، يُثبت أن التغيير الجذري يبدأ دائماً من خطوات صغيرة متراكمة.',
    },
  ];
})();
