/* ============================================================
   books-data.js — Derradj Shop | بيانات قسم الكتب
   catalogId يجب أن يتطابق مع SHOP_CATALOG في cart.js
   ============================================================ */

window.BOOKS_DATA = (function () {
  'use strict';

  return [
    {
      id: 2, title: 'العادات السبع للناس الأكثر فعالية', titleEn: 'The 7 Habits of Highly Effective People',
      author: 'ستيفن آر. كوفي', translator: 'هشام عبد الله', year: 1989,
      category: 'تطوير الذات', price: 1400, image: '7-habits/main.png', url: '7-habits/',
      available: true,
      description: 'سبعة مبادئ لبناء الشخصية الفعّالة والنجاح في الحياة الشخصية والمهنية والاجتماعية، مبنية على قيم راسخة ونظرة عميقة للإنسان.',
    },
    {
      id: 3, title: 'العادات الذرية', titleEn: 'Atomic Habits',
      author: 'جيمس كلير', translator: 'محمد فتحي خضر', year: 2018,
      category: 'تطوير الذات', price: 950, image: 'atomic-habits/main.png', url: 'atomic-habits/',
      available: true,
      description: 'استراتيجيات علمية وعملية لبناء عادات إيجابية والتخلص من العادات السلبية عبر تغييرات صغيرة تتراكم لتُحدث نتائج استثنائية.',
    },
    {
      id: 4, title: 'قاعدة الـ 333', titleEn: 'Rule 3-3-3',
      author: 'شهاب الهاشمي', translator: null, year: 2024,
      category: 'تطوير الذات', price: 1350, image: 'rule-333/main.png', url: 'rule-333/',
      available: true,
      description: 'خلاصات وأفكار قيّمة في العلاقات العامة وصناعة المحتوى الرقمي وبناء الحضور الشخصي عبر قاعدة مبسّطة وفعّالة.',
    },
    {
      id: 6, title: 'متعة عدم الكمال', titleEn: 'The Joy of Imperfection',
      author: 'ديمون زهاريادس', translator: null, year: 2017,
      category: 'تطوير الذات', price: 1800, image: 'joy-of-imperfection/main.png', url: 'joy-of-imperfection/',
      available: true,
      description: 'دليل شامل للتغلب على وسواس الكمالية وإسكات الناقد الداخلي، واكتشاف أن النقص الإنساني هو أصل الجمال والتطور.',
    },
    {
      id: 7, title: 'الشجاعة تنادي', titleEn: 'Courage Is Calling',
      author: 'ريان هوليداي', translator: 'محمد أقديم', year: 2021,
      category: 'الفلسفة والفكر', price: 1300, image: 'courage-is-calling/main.png', url: 'courage-is-calling/',
      available: true,
      description: 'عبر قصص تاريخية ملهمة يستكشف الكاتب معنى الشجاعة الحقيقية وكيف نتغلب على الخوف الذي يمنعنا من تحقيق أهدافنا.',
    },
    {
      id: 8, title: 'قوة الآن', titleEn: 'The Power of Now',
      author: 'إيكهارت تول', translator: 'مينا كمال', year: 1997,
      category: 'الفلسفة والفكر', price: 1100, image: 'power-of-now/main.png', url: 'power-of-now/',
      available: true,
      description: 'دليل روحي عميق للعيش في اللحظة الراهنة والتحرر من قيود الماضي وقلق المستقبل لتحقيق السلام الداخلي الحقيقي.',
    },
    {
      id: 9, title: 'بروباغندا', titleEn: 'Propaganda',
      author: 'إدوارد بيرنايز', translator: 'يحيى العريضي', year: 1928,
      category: 'علم النفس والمجتمع', price: 1100, image: 'propaganda/main.png', url: 'propaganda/',
      available: true,
      description: 'الكتاب الأصل في علم العلاقات العامة يكشف آليات التأثير في الجماهير والرأي العام وكيف يمكن توجيه سلوك الناس على نطاق واسع.',
    },
    {
      id: 10, title: 'فوضى الإدارة', titleEn: 'Management Mess to Leadership Success',
      author: 'سكوت جيفري ميلر', translator: null, year: 2019,
      category: 'الإدارة والأعمال', price: 1600, image: 'management-mess/main.png', url: 'management-mess/',
      available: true,
      description: 'ثلاثون تحدياً حقيقياً يواجهها القادة في مسيرتهم المهنية، مع حلول عملية وتجارب واقعية للتغلب عليها.',
    },
    {
      id: 11, title: 'السعادة الحقيقية والسعادة الزائفة', titleEn: 'The Myths of Happiness',
      author: 'سونيا ليوبوميرسكي', translator: 'سمر حجازي', year: 2013,
      category: 'علم النفس والمجتمع', price: 1600, image: 'myths-of-happiness/main.png', url: 'myths-of-happiness/',
      available: true,
      description: 'تدحض الباحثة النفسية الأساطير الشائعة حول مصادر السعادة وتقدم بدائل علمية مستندة إلى أبحاث موثقة لبناء سعادة حقيقية ومستدامة.',
    },
    {
      id: 12, title: 'مسارات السعادة', titleEn: 'Happy Ever After',
      author: 'بول دولان', translator: null, year: 2019,
      category: 'علم النفس والمجتمع', price: 1300, image: 'happy-ever-after/main.png', url: 'happy-ever-after/',
      available: true,
      description: 'اكتشاف معنى السعادة الحقيقية بتجاوز القوالب النمطية والتوقعات الاجتماعية، بقلم أحد أبرز الباحثين في علم الاقتصاد السلوكي.',
    },
    {
      id: 13, title: 'في عالم الأشباح الجائعة', titleEn: 'In the Realm of Hungry Ghosts',
      author: 'غابور ماتيه', translator: null, year: 2008,
      category: 'علم النفس والمجتمع', price: 1800, image: 'hungry-ghosts/main.png', url: 'hungry-ghosts/',
      available: true,
      description: 'استكشاف عميق للجذور النفسية والاجتماعية للإدمان والصدمات النفسية وكيفية التعافي منها بأسلوب إنساني وعلمي رائع.',
    },
    {
      id: 14, title: 'تاريخ موجز للزمان', titleEn: 'A Brief History of Time',
      author: 'ستيفن هوكينج', translator: 'د. أدهم السمّان', year: 1988,
      category: 'العلوم والمعرفة', price: 1200, image: 'brief-history-of-time/main.png', url: 'brief-history-of-time/',
      available: true,
      description: 'رحلة علمية مبسّطة ورائعة في أعماق الكون من أصغر الجسيمات إلى أسرار الزمان والمكان والثقوب السوداء وأصل الكون.',
    },
    {
      id: 16, title: 'متعة أن تكون في الثلاثين', titleEn: 'The Joy of Being Thirty',
      author: 'علا ديوب', translator: null, year: 2019,
      category: 'تطوير الذات', price: 950, image: 'joy-of-thirties/main.png', url: 'joy-of-thirties/',
      available: true,
      description: 'مقالات متنوعة وملهمة حول مرحلة الثلاثينيات وما تحمله من نضج وخبرة وتحولات عميقة في الرؤية للذات والعالم.',
    },
    {
      id: 17, title: 'كن مع الشخص الذي يجعلك سعيداً', titleEn: 'Be with the One Who Makes You Happy',
      author: 'مؤلفون مختلفون', translator: null, year: null,
      category: 'العلاقات والحياة', price: 1200, image: 'be-happy-with-someone/main.png', url: 'be-happy-with-someone/',
      available: true,
      description: 'أهمية البيئة الداعمة واختيار الشريك المناسب لبناء حياة مليئة بالسعادة والانسجام والنمو الشخصي المشترك.',
    },
    {
      id: 20, title: 'الذكاء العاطفي', titleEn: 'Emotional Intelligence',
      author: 'دانيال جولمان', translator: 'ليلى الجبالي', year: 1995,
      category: 'علم النفس والمجتمع', price: 1600, image: 'emotional-intelligence/main.png', url: 'emotional-intelligence/',
      available: true,
      description: 'كيف يتفوق الذكاء العاطفي على معدل الذكاء التقليدي في تحقيق النجاح وبناء العلاقات وإدارة المشاعر والتعامل مع التحديات.',
    },
    {
      id: 21, title: 'كيف تبيع أي شيء لأي إنسان', titleEn: 'How to Sell Anything to Anybody',
      author: 'جو جيرارد', translator: null, year: 1977,
      category: 'الإدارة والأعمال', price: 1100, image: 'sell-anything/main.png', url: 'sell-anything/',
      available: true,
      description: 'أسرار المبيعات من أفضل بائع في العالم وفقاً لموسوعة غينيس، مع أساليب عملية وقصص واقعية تُغير طريقة التفكير في البيع.',
    },
    {
      id: 22, title: 'كيف تسوق نفسك', titleEn: 'How to Sell Yourself',
      author: 'جو جيرارد', translator: null, year: 1979,
      category: 'الإدارة والأعمال', price: 1700, image: 'sell-yourself/main.png', url: 'sell-yourself/',
      available: true,
      description: 'من أفضل بائع في العالم وفقاً لغينيس — دليل عملي لتسويق شخصيتك وقدراتك في الحياة والعمل، لأن البيع الأول دائماً هو بيع نفسك.',
    },
    {
      id: 23, title: 'كيف تتقن إتمام الصفقات', titleEn: 'How to Close Every Sale',
      author: 'جو جيرارد', translator: null, year: 1989,
      category: 'الإدارة والأعمال', price: 1500, image: 'mastering-deals/main.png', url: 'mastering-deals/',
      available: true,
      description: 'تقنيات احترافية لإغلاق الصفقات وتحويل كل فرصة إلى نتيجة ناجحة، مستخلصة من تجربة ميدانية حقيقية لأعظم مندوب مبيعات في التاريخ.',
    },
    {
      id: 24, title: 'سيكولوجية المال', titleEn: 'The Psychology of Money',
      author: 'مورجان هاوسل', translator: null, year: 2020,
      category: 'الإدارة والأعمال', price: 1600, image: 'psychology-of-money/main.png', url: 'psychology-of-money/',
      available: true,
      description: 'كيف تؤثر مشاعرنا وتحيزاتنا وسلوكياتنا على قراراتنا المالية أكثر من المعرفة التقنية — درس عميق في علاقة الإنسان بالمال وطريق بناء الثروة الحقيقية.',
    },
    {
      id: 25, title: 'العقل الباطن', titleEn: 'The Subconscious Mind',
      author: 'فيكتور بوشيه', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 950, image: 'subconscious-mind/main.png', url: 'subconscious-mind/',
      available: true,
      description: 'رحلة استكشافية في أعماق العقل الباطن وآلياته الخفية التي تحرك سلوكنا وقراراتنا وعلاقاتنا دون وعي منّا، مع أساليب للتحكم فيها والاستفادة منها.',
    },
    {
      id: 26, title: 'فن اللامبالاة', titleEn: 'The Subtle Art of Not Giving a F*ck',
      author: 'مارك مانسون', translator: null, year: 2016,
      category: 'تطوير الذات', price: 900, image: 'subtle-art/main.png', url: 'subtle-art/',
      available: true,
      description: 'مقاربة استفزازية ومختلفة لحياة أفضل — تعلّم كيف تختار ما تهتم به بعناية، وتتخلى عما لا يستحق طاقتك، لتعيش بحرية وأصالة حقيقية.',
    },
    {
      id: 27, title: 'سيكولوجية الجماهير', titleEn: 'The Crowd',
      author: 'غوستاف لوبون', translator: null, year: 1895,
      category: 'علم النفس والمجتمع', price: 750, image: 'crowd-psychology/main.png', url: 'crowd-psychology/',
      available: true,
      description: 'الكتاب الكلاسيكي الذي أسّس علم نفس الجماهير — يكشف كيف تفكر الحشود وتتصرف بطريقة مختلفة كلياً عن الأفراد، ولماذا يُعدّ من أكثر الكتب تأثيراً في التاريخ.',
    },
    {
      id: 28, title: 'السنن النفسية لتطور الأمم', titleEn: 'The Psychology of Peoples',
      author: 'غوستاف لوبون', translator: null, year: 1894,
      category: 'علم النفس والمجتمع', price: 1300, image: 'psychological-laws/main.png', url: 'psychological-laws/',
      available: true,
      description: 'دراسة معمّقة في الخصائص النفسية للشعوب وكيف تحدد شخصيتها الجماعية مساراتها الحضارية والتاريخية — إسهام فريد في فهم الديناميكيات الاجتماعية للأمم.',
    },
    {
      id: 29, title: 'الآراء والمعتقدات', titleEn: 'The Psychology of Revolution',
      author: 'غوستاف لوبون', translator: null, year: 1912,
      category: 'علم النفس والمجتمع', price: 1550, image: 'opinions-beliefs/main.png', url: 'opinions-beliefs/',
      available: true,
      description: 'كيف تتشكّل الآراء والمعتقدات الجماعية وتنتشر في المجتمعات — تحليل نفسي دقيق لآليات التأثير والإقناع الجماهيري من أبرز علماء النفس الاجتماعي.',
    },
    {
      id: 30, title: 'الذكر العقلاني: الذكورة الإيجابية', titleEn: 'The Rational Male',
      author: 'رولو توماسي', translator: null, year: 2013,
      category: 'تطوير الذات', price: 2100, image: 'rational-male/main.png', url: 'rational-male/',
      available: true,
      description: 'مرجع شامل يستكشف الديناميكيات النفسية للعلاقات بين الجنسين والهوية الذكورية، مقدّماً رؤية عقلانية وموضوعية لفهم الذكورة الإيجابية وبناء الشخصية القوية.',
    },
    {
      id: 31, title: '6 مهارات لتحقيق مبيعات مختلفة مذهلة', titleEn: '6 Skills to Super-Charge Your Sales',
      author: 'ديل ميريل، جينيفر كولوسيمو، سكوت سافاج، راندي إلينج', translator: null, year: null,
      category: 'الإدارة والأعمال', price: 1400, image: '6-sales-skills/main.png', url: '6-sales-skills/',
      available: true,
      description: 'ست مهارات عملية مجرّبة لرفع مستوى أدائك في المبيعات إلى آفاق جديدة — دليل ميداني من خبراء متخصصين لتحقيق نتائج مذهلة في بيئات المبيعات التنافسية.',
    },
    {
      id: 32, title: 'الأثر المذهل للعادات البسيطة', titleEn: 'Small Habits Revolution',
      author: 'ديمون زهاريادس', translator: null, year: 2018,
      category: 'تطوير الذات', price: 1800, image: 'small-habits-effect/main.png', url: 'small-habits-effect/',
      available: true,
      description: 'الطبعة المحدّثة والموسّعة — دليل شامل لاكتساب عادات مستدامة بأساليب علمية مجرّبة، يُثبت أن التغيير الجذري يبدأ دائماً من خطوات صغيرة متراكمة.',
    },
    {
      id: 33, title: 'العادات السبع للمراهقين الأكثر فعالية', titleEn: 'The 7 Habits of Highly Effective Teens',
      author: 'شين كوفي', translator: null, year: 1998,
      category: 'تطوير الذات', price: 1100, image: '7-habits-teens/main.png', url: '7-habits-teens/',
      available: true,
      description: 'نسخة مُكيَّفة خصيصاً للمراهقين من الكتاب الأشهر في تطوير الذات — سبعة مبادئ عملية تساعد الشباب على بناء شخصية قوية وتحقيق أهدافهم بثقة.',
    },
    {
      id: 34, title: 'القائد في داخلي', titleEn: 'The Leader in Me',
      author: 'ستيفن آر. كوفي', translator: null, year: 2008,
      category: 'تطوير الذات', price: 1300, image: 'leader-in-me/main.png', url: 'leader-in-me/',
      available: true,
      description: 'كيف تُنمّي قيادة حقيقية من الداخل — يُقدّم كوفي نموذجاً تحويلياً لبناء شخصية قيادية مستدامة تنبع من القيم والمبادئ لا من المناصب والألقاب.',
    },
    {
      id: 35, title: 'الأنوثة المظلمة', titleEn: 'Dark Feminine Power',
      author: 'كاثرين جيمس', translator: null, year: null,
      category: 'تطوير الذات', price: 800, image: 'dark-feminine-power/main.png', url: 'dark-feminine-power/',
      available: true,
      description: 'استكشاف الجانب المظلم من الطاقة الأنثوية وكيفية تحويله إلى قوة داخلية أصيلة — رحلة في اكتشاف الذات والتحرر من القوالب الاجتماعية المفروضة.',
    },
    {
      id: 36, title: 'لماذا لا تذهب الخراف إلى الطبيب؟', titleEn: 'Why Sheep Don\'t Go to the Doctor',
      author: 'فهد عامر الأحمدي / د. نجاة سعيد الأحمدي', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 1100, image: 'why-sheep-dont-go-to-doctor/main.png', url: 'why-sheep-dont-go-to-doctor/',
      available: true,
      description: 'نظرة نقدية وتحليلية بالغة الطرافة لمفارقات السلوك البشري — يطرح الكتاب أسئلة عميقة حول العقلانية والاستسلام والحواجز النفسية التي تمنعنا من طلب المساعدة.',
    },
    {
      id: 37, title: 'من صفر إلى واحد: ملاحظات حول الشركات الناشئة، أو كيفية بناء المستقبل', titleEn: 'Zero to One',
      author: 'بيتر ثيل، بليك ماسترز', translator: null, year: 2014,
      category: 'الإدارة والأعمال', price: 850, image: 'zero-to-one/main.png', url: 'zero-to-one/',
      available: true,
      description: 'من المؤسس المشارك لـ PayPal — رؤية ثاقبة حول بناء شركات ناشئة استثنائية تخلق شيئاً جديداً تماماً، وليس مجرد نسخ ما هو موجود.',
    },
    {
      id: 38, title: 'اللطف وآثاره الجانبية الخمسة', titleEn: 'The Five Side Effects of Kindness',
      author: 'ديفيد هاميلتون', translator: null, year: 2017,
      category: 'علم النفس والمجتمع', price: 950, image: 'kindness-side-effects/main.png', url: 'kindness-side-effects/',
      available: true,
      description: 'دراسة علمية مُدهشة تُثبت أن اللطف لا يفيد الآخرين فحسب، بل له آثار جانبية إيجابية عميقة على الصحة الجسدية والنفسية للشخص اللطيف نفسه.',
    },
    {
      id: 39, title: 'طاقة الأنوثة: اختبار ورفع مستوى السعادة والإبداع في حياتك', titleEn: 'Feminine Energy',
      author: 'كاثرين جيمس', translator: null, year: null,
      category: 'تطوير الذات', price: 900, image: 'feminine-energy/main.png', url: 'feminine-energy/',
      available: true,
      description: 'دليل عملي لاكتشاف الطاقة الأنثوية الكامنة وتوظيفها لرفع مستوى السعادة والإبداع في مختلف مجالات الحياة الشخصية والمهنية.',
    },
    {
      id: 40, title: 'ممتلئ بالفراغ: تأملات حول التعافي من الإدمانات والسلوكيات القهرية', titleEn: 'Full of Emptiness',
      author: 'د. عماد رشاد عثمان', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 1400, image: 'full-of-emptiness/main.png', url: 'full-of-emptiness/',
      available: true,
      description: 'تأملات عميقة في جذور الإدمان والسلوكيات القهرية وكيفية التعافي منها — نهج نفسي إنساني يدمج بين الفهم العلمي والبُعد الروحي للشفاء.',
    },
    {
      id: 41, title: 'أبي الذي أكره: تأملات حول التعافي من إساءات الأبوين وصدمات النشأة', titleEn: 'The Father I Hate',
      author: 'د. عماد رشاد عثمان', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 1100, image: 'father-i-hate/main.png', url: 'father-i-hate/',
      available: true,
      description: 'دراسة نفسية جريئة في إساءات الوالدين وصدمات الطفولة وأثرها الممتد على البالغين — مع مسارات عملية نحو التعافي وإعادة بناء الذات.',
    },
    {
      id: 42, title: 'بلورة الرأي العام', titleEn: 'Crystallizing Public Opinion',
      author: 'إدوارد بيرنايز', translator: null, year: 1923,
      category: 'علم النفس والمجتمع', price: 1100, image: 'crystallizing-public-opinion/main.png', url: 'crystallizing-public-opinion/',
      available: true,
      description: 'الكتاب الرائد لمؤسس العلاقات العامة الحديثة — يكشف كيف يُشكَّل الرأي العام ويُوجَّه، وما هي الأدوات والتقنيات التي تُحرّك المجتمعات وتصنع الموافقة الجماهيرية.',
    },
    {
      id: 43, title: 'بوابتك للتغيير', titleEn: null,
      author: 'نواف العثمان', translator: null, year: null,
      category: 'تطوير الذات', price: 950, image: 'bawabatuka-liltaghyir/main.png', url: 'bawabatuka-liltaghyir/',
      available: true,
      description: 'كتاب في تطوير الذات يساعد القارئ على فهم خطوات التغيير الشخصي وبناء عادات وأفكار أفضل لحياة أكثر وعيًا وتوازنًا.',
    },
    {
      id: 44, title: 'أغنى رجل في بابل', titleEn: 'The Richest Man in Babylon',
      author: 'جورج صامويل كلاسون', translator: null, year: 1926,
      category: 'الإدارة والأعمال', price: 950, image: 'richest-man-in-babylon/main.png', url: 'richest-man-in-babylon/',
      available: true,
      description: 'كتاب كلاسيكي في الثقافة المالية يقدم مبادئ بسيطة حول الادخار، إدارة المال، وبناء الثروة من خلال قصص وحِكم مدينة بابل القديمة.',
    },
    {
      id: 45, title: 'أريد أن أنام', titleEn: null,
      author: 'هارييت جريفي', translator: null, year: null,
      category: 'الروايات والأدب', price: 850, image: 'urid-an-anam/main.png', url: 'urid-an-anam/',
      available: true,
      description: 'كتاب يساعد الأطفال على الاسترخاء والاستعداد للنوم من خلال أسلوب هادئ ولطيف، مناسب لوقت النوم ويشجع على الطمأنينة والراحة.',
    },
    {
      id: 46, title: 'كيف لا تموت وحيدًا', titleEn: 'How Not to Die Alone',
      author: 'لوغان أوري', translator: null, year: 2021,
      category: 'العلاقات والحياة', price: 1300, image: 'how-not-to-die-alone/main.png', url: 'how-not-to-die-alone/',
      available: true,
      description: 'كتاب عملي في العلاقات العاطفية يساعد القارئ على فهم اختياراته وبناء علاقة صحية بعيدًا عن الأخطاء المتكررة في الحب والارتباط.',
    },
    {
      id: 47, title: 'كن أقوى من مشاعرك', titleEn: 'Emotionally Stronger',
      author: 'باتريك كينغ', translator: null, year: null,
      category: 'تطوير الذات', price: 1400, image: 'stronger-than-your-emotions/main.png', url: 'stronger-than-your-emotions/',
      available: true,
      description: 'كتاب في الذكاء العاطفي والتحكم بالمشاعر، يقدم طرقًا عملية لفهم الانفعالات والتعامل معها بقوة ووعي أكبر.',
    },
    {
      id: 48, title: 'تصرفي كسيدة وفكري كرجل', titleEn: 'Act Like a Lady, Think Like a Man',
      author: 'ستيف هارفي', translator: null, year: 2009,
      category: 'العلاقات والحياة', price: 950, image: 'act-like-a-lady-think-like-a-man/main.png', url: 'act-like-a-lady-think-like-a-man/',
      available: true,
      description: 'كتاب في العلاقات يشرح بطريقة مباشرة كيف يفكر الرجال في الحب والالتزام، ويقدم نصائح للمرأة لفهم العلاقات بشكل أوضح.',
    },
    {
      id: 49, title: 'كبر دماغك', titleEn: null,
      author: 'د. خالد المنيف', translator: null, year: null,
      category: 'تطوير الذات', price: 950, image: 'kabber-dmaghak/main.png', url: 'kabber-dmaghak/',
      available: true,
      description: 'كتاب خفيف في تطوير الذات وفن التعامل مع ضغوط الحياة، يساعد القارئ على تبسيط الأمور وعدم إعطاء المشاكل أكبر من حجمها.',
    },
    {
      id: 50, title: 'قوانين النجاح المستدام: كيف تستمر في النجاح', titleEn: 'Laws of Sustainable Success',
      author: 'غير مؤكد', translator: null, year: null,
      category: 'تطوير الذات', price: 900, image: 'qawanin-al-najah-al-mustadam/main.png', url: 'qawanin-al-najah-al-mustadam/',
      available: true,
      description: 'كتاب في النجاح وتطوير الأداء الشخصي يركز على الاستمرارية، الانضباط، وبناء أسلوب حياة يساعد على المحافظة على الإنجاز.',
    },
    {
      id: 51, title: 'كيف نحصل على السعادة ونبتعد عن الكآبة', titleEn: 'The Laws of the Sun',
      author: 'ريوهو أوكاوا', translator: null, year: null,
      category: 'العلاقات والحياة', price: 850, image: 'happiness-and-depression/main.png', url: 'happiness-and-depression/',
      available: true,
      description: 'كتاب يقدم أفكارًا حول السعادة، التفكير الإيجابي، والتخلص من المشاعر السلبية من أجل حياة أكثر هدوءًا ورضا.',
    },
    {
      id: 52, title: 'هل ستأكل قطتي مقلتي؟', titleEn: 'Will My Cat Eat My Eyeballs?',
      author: 'كيتلين دوتي', translator: null, year: 2019,
      category: 'العلوم والمعرفة', price: 2400, image: 'will-my-cat-eat-my-eyeballs/main.png', url: 'will-my-cat-eat-my-eyeballs/',
      available: true,
      description: 'كتاب غريب وممتع يجيب عن أسئلة الأطفال حول الموت والجسد بأسلوب مبسط، علمي، وصريح مع لمسة من الفكاهة.',
    },
    {
      id: 53, title: 'الوحش الذي يسكنك يمكن أن يكون لطيفًا', titleEn: null,
      author: 'غير مؤكد', translator: null, year: null,
      category: 'الفلسفة والفكر', price: 1400, image: 'the-monster-inside-you-can-be-kind/main.png', url: 'the-monster-inside-you-can-be-kind/',
      available: true,
      description: 'كتاب في فهم الذات والمشاعر الداخلية، يدعو القارئ إلى التصالح مع جانبه الخفي وتحويل الألم الداخلي إلى لطف ووعي.',
    },
    {
      id: 54, title: 'احرق بعد الكتابة', titleEn: 'Burn After Writing',
      author: 'شارون جونز', translator: null, year: 2015,
      category: 'تطوير الذات', price: 950, image: 'burn-after-writing/main.png', url: 'burn-after-writing/',
      available: true,
      description: 'كتاب تفاعلي يعتمد على الكتابة الشخصية والأسئلة العميقة، يساعد القارئ على التعبير عن نفسه واكتشاف أفكاره ومشاعره بصدق.',
    },
    {
      id: 55, title: 'عين الأنا: الذي لا يُخفى عنه شيء', titleEn: 'The Eye of the I',
      author: 'د. ديفيد ر. هاوكينز', translator: null, year: 2001,
      category: 'الفلسفة والفكر', price: 1300, image: 'the-eye-of-the-i/main.png', url: 'the-eye-of-the-i/',
      available: true,
      description: 'كتاب في الوعي والروحانيات يناقش طبيعة الأنا والإدراك الداخلي، ويقود القارئ نحو فهم أعمق للذات والحقيقة.',
    },
    {
      id: 56, title: 'وأشرقت الشمس من جديد', titleEn: 'The Sun Does Shine',
      author: 'أنتوني راي هينتون مع لارا لوف هاردن', translator: null, year: 2018,
      category: 'الروايات والأدب', price: 1300, image: 'the-sun-does-shine/main.png', url: 'the-sun-does-shine/',
      available: true,
      description: 'مذكرات مؤثرة لرجل قضى سنوات طويلة في السجن ظلمًا، تحكي قصة الصبر، الأمل، العدالة، والقدرة على النهوض بعد المعاناة.',
    },
    /* ══════════════════════════════════════════════════════════
       كتب جديدة — IDs 57–82
    ══════════════════════════════════════════════════════════ */
    {
      id: 57, title: 'كتاب المليونير', titleEn: 'The Millionaire',
      author: 'مارك فيشر', translator: null, year: null,
      category: 'تطوير الذات', price: 1200, image: 'kitab-al-millionaire/main.png', url: 'kitab-al-millionaire/',
      available: true,
      description: 'قصة ملهمة تروي حكمة الملياردير في طريق الثروة والنجاح المالي، بأسلوب سردي بسيط يكشف قوانين الوفرة والتفكير الإيجابي نحو بناء الثروة الحقيقية.',
    },
    {
      id: 58, title: 'السنارة: كل شيء عن ريادة الأعمال الابتكارية', titleEn: 'Al-Sannara',
      author: 'البروفيسور مير أحمد', translator: null, year: null,
      category: 'الإدارة والأعمال', price: 1300, image: 'al-sannara/main.png', url: 'al-sannara/',
      available: true,
      description: 'دليل شامل في ريادة الأعمال الابتكارية يكشف أسرار بناء مشاريع ناجحة من خلال التفكير الإبداعي وإيجاد الحلول غير التقليدية في بيئة الأعمال الحديثة.',
    },
    {
      id: 59, title: 'تجاوز مستويات الوعي: الطريق إلى التنوير', titleEn: 'Transcending the Levels of Consciousness',
      author: 'ديفيد ر. هاوكينز', translator: 'محمد مشكاف', year: null,
      category: 'الفلسفة والفكر', price: 1300, image: 'tajawoz-mostawayat-al-waai/main.png', url: 'tajawoz-mostawayat-al-waai/',
      available: true,
      description: 'خارطة طريق علمية وروحية نحو التنوير والارتقاء بمستويات الوعي الإنساني، بقلم أحد أبرز أطباء الطب النفسي والباحثين في علم الوعي.',
    },
    {
      id: 60, title: 'هذا الكتاب سيؤلمك: يوميات سرية لطبيب مبتدئ', titleEn: 'This Is Going to Hurt',
      author: 'آدم كاي', translator: 'محمد الضبع', year: 2017,
      category: 'الروايات والأدب', price: 950, image: 'hatha-alkitab-sayuulimuk/main.png', url: 'hatha-alkitab-sayuulimuk/',
      available: true,
      description: 'يوميات ساخرة ومؤلمة لطبيب في مستهل مسيرته تكشف الواقع الحقيقي لمهنة الطب خلف الأبواب المغلقة، بأسلوب مباشر وإنساني لا يُنسى.',
    },
    {
      id: 61, title: 'الخطابات السرية للراهب الذي باع سيارته الفيراري', titleEn: 'The Secret Letters of the Monk Who Sold His Ferrari',
      author: 'روبن شارما', translator: null, year: null,
      category: 'تطوير الذات', price: 950, image: 'al-khitabat-al-sirriya/main.png', url: 'al-khitabat-al-sirriya/',
      available: true,
      description: 'رسائل حكمة خاصة تكشف أسراراً لم تُقَل في الكتاب الأصلي — رحلة أعمق في التفكير الإيجابي وبناء الحياة التي تستحقها بالمعايير الصحيحة.',
    },
    {
      id: 62, title: 'الراهب الذي باع سيارته الفيراري', titleEn: 'The Monk Who Sold His Ferrari',
      author: 'روبن شارما', translator: null, year: 1997,
      category: 'تطوير الذات', price: 950, image: 'al-rahib-allathi-baa/main.png', url: 'al-rahib-allathi-baa/',
      available: true,
      description: 'رواية ملهمة تحكي رحلة محامٍ ناجح يترك حياة الثروة والمجد ليكتشف أسرار السعادة الحقيقية والحكمة الروحية في دير جبلي بالهيمالايا.',
    },
    {
      id: 63, title: 'القوانين اليومية: 366 فكرة تأملية في القوة والإغواء والإتقان والاستراتيجية والطبيعة البشرية', titleEn: 'The Daily Laws',
      author: 'روبرت غرين', translator: null, year: 2021,
      category: 'تطوير الذات', price: 1900, image: 'daily-laws/main.png', url: 'daily-laws/',
      available: true,
      description: '366 فكرة تأملية يومية مستخلصة من أشهر كتب روبرت غرين في القوة والإغواء والإتقان والاستراتيجية والطبيعة البشرية — حكمة يومية لبناء شخصية استثنائية.',
    },
    {
      id: 64, title: 'فن الإغواء', titleEn: 'The Art of Seduction',
      author: 'روبرت غرين', translator: null, year: 2001,
      category: 'علم النفس والمجتمع', price: 3200, image: 'art-of-seduction/main.png', url: 'art-of-seduction/',
      available: true,
      description: 'دراسة معمّقة في علم الإغواء والتأثير من خلال التاريخ والنفس البشرية — يكشف القوى الخفية التي تجذب الناس وتُسيطر على قراراتهم العاطفية والاجتماعية.',
    },
    {
      id: 65, title: 'فن التعامل مع الناس', titleEn: 'How to Win Friends and Influence People',
      author: 'ديل كارنيجي', translator: null, year: 1936,
      category: 'تطوير الذات', price: 650, image: 'fan-altaamal-maa-alnas/main.png', url: 'fan-altaamal-maa-alnas/',
      available: true,
      description: 'الكتاب الأكثر مبيعاً في تاريخ كتب التطوير الذاتي — مهارات التواصل والتأثير الإيجابي في الناس لبناء علاقات ناجحة وتحقيق الأهداف الشخصية والمهنية.',
    },
    {
      id: 66, title: 'فن الإدارة والقيادة', titleEn: 'The Art of Management and Leadership',
      author: 'ديل كارنيجي', translator: null, year: null,
      category: 'الإدارة والأعمال', price: 700, image: 'fan-alidara-walqiyada/main.png', url: 'fan-alidara-walqiyada/',
      available: true,
      description: 'مبادئ الإدارة الفعّالة والقيادة الناجحة من قلم كارنيجي — أساليب عملية لإدارة الفرق وتحفيز الموظفين وبناء بيئة عمل تحقق نتائج استثنائية.',
    },
    {
      id: 67, title: 'دع القلق وابدأ الحياة', titleEn: 'How to Stop Worrying and Start Living',
      author: 'ديل كارنيجي', translator: 'عبد المنعم الزيادي', year: 1948,
      category: 'تطوير الذات', price: 650, image: 'daa-alqalaq-wabda-alhayat/main.png', url: 'daa-alqalaq-wabda-alhayat/',
      available: true,
      description: 'الكتاب الكلاسيكي الذي تُرجم لعشرات اللغات — استراتيجيات مجرّبة للتحرر من القلق والتوتر والخوف والعيش بطاقة إيجابية وتركيز على ما يهم فعلاً.',
    },
    {
      id: 68, title: 'خطة تسويق في صفحة واحدة', titleEn: 'The 1-Page Marketing Plan',
      author: 'ألن ديب', translator: null, year: 2016,
      category: 'الإدارة والأعمال', price: 1200, image: 'one-page-marketing-plan/main.png', url: 'one-page-marketing-plan/',
      available: true,
      description: 'نظام تسويقي بسيط وفعّال يمكن تطبيقه فوراً — خارطة طريق عملية لبناء استراتيجية تسويقية واضحة تجلب العملاء وتُنمّي الأعمال باستمرار وبتكلفة معقولة.',
    },
    {
      id: 69, title: 'فوضى التسويق', titleEn: 'Marketing Mess to Brand Success',
      author: 'سكوت جيفري ميلر', translator: null, year: 2021,
      category: 'الإدارة والأعمال', price: 1750, image: 'fowda-altasweq/main.png', url: 'fowda-altasweq/',
      available: true,
      description: 'رؤية مغايرة لعالم التسويق الحديث تكشف الأخطاء الشائعة وتقدم بدائل فعّالة لبناء علامة تجارية قوية والتميز في السوق التنافسي بأسلوب صريح وعملي.',
    },
    {
      id: 70, title: 'معجزة الصباح', titleEn: 'The Miracle Morning',
      author: 'هال إلرود', translator: 'معن عاقل', year: 2012,
      category: 'تطوير الذات', price: 1100, image: 'miracle-morning/main.png', url: 'miracle-morning/',
      available: true,
      description: 'اكتشف كيف تُحدث ساعة الصباح الأولى ثورة في حياتك كلها — روتين صباحي مُثبَت علمياً يُطور صحتك الجسدية والعقلية والمهنية والروحية في وقت واحد.',
    },
    {
      id: 71, title: 'معسكر التدريب', titleEn: 'Training Camp',
      author: 'جون جوردون', translator: null, year: 2009,
      category: 'تطوير الذات', price: 950, image: 'training-camp/main.png', url: 'training-camp/',
      available: true,
      description: 'قصة ملهمة لفريق رياضي يواجه تحديات الفشل والانهيار ويتعلم مبادئ القيادة والتضامن والإصرار على النجاح من خلال تجربة معسكر التدريب الاستثنائية.',
    },
    {
      id: 72, title: 'متلازمة تيك توك: كيف يغير تطبيق واحد العالم من حولنا؟', titleEn: null,
      author: 'إسماعيل عرفة', translator: null, year: null,
      category: 'علم النفس والمجتمع', price: 1400, image: 'tiktok-syndrome/main.png', url: 'tiktok-syndrome/',
      available: true,
      description: 'تحليل ثري لتأثير التطبيقات الاجتماعية وخاصة تيك توك على طريقة تفكيرنا وسلوكنا وعلاقاتنا في عصر الخوارزميات والانتباه المشتت — الكتاب عربي أصيل.',
    },
    {
      id: 73, title: 'قوة الحب المذهلة', titleEn: 'The Astonishing Power of Love',
      author: 'ستيفاني بريليانت', translator: 'منال ممدوح', year: null,
      category: 'العلاقات والحياة', price: 1700, image: 'quwwat-alhub-almudhila/main.png', url: 'quwwat-alhub-almudhila/',
      available: true,
      description: 'رحلة في فهم طبيعة الحب وتأثيره المذهل على النفس والجسد والعلاقات — دليل نفسي دافئ لبناء روابط عاطفية قوية وصحية ومستدامة مع من نُحب.',
    },
    {
      id: 74, title: 'مميز بالأصفر', titleEn: 'Highlighted in Yellow',
      author: 'إتش. جاكسون براون وروتشيل بنينجتون', translator: null, year: null,
      category: 'تطوير الذات', price: 950, image: 'mumayaz-bil-asfar/main.png', url: 'mumayaz-bil-asfar/',
      available: true,
      description: 'مجموعة من أجمل الاقتباسات والأفكار الملهمة التي تستحق التأمل والتطبيق — حكمة مكثفة ونصائح ذهبية تُضاء بخط التمييز الأصفر في كل صفحة تقرأها.',
    },
    {
      id: 75, title: 'ملول وعبقري: إعادة اكتشاف فن الشرود المفقود', titleEn: 'Bored and Brilliant',
      author: 'مانوش زمردي', translator: 'فرح عمران', year: 2017,
      category: 'تطوير الذات', price: 950, image: 'bored-and-brilliant/main.png', url: 'bored-and-brilliant/',
      available: true,
      description: 'كشف علمي ومثير لقيمة الملل وشرود الذهن في تحفيز الإبداع والابتكار — الشرود ليس هدراً بل هو عقلك في أفضل حالاته الإبداعية والتأملية.',
    },
    {
      id: 76, title: 'الحياة تخطيط: انتقاء الخيارات الحكيمة وسط عالم مضطرب', titleEn: 'Life Planning',
      author: 'ريك كيرشنر وريك برينكمان', translator: null, year: null,
      category: 'تطوير الذات', price: 1200, image: 'alhayat-takhtit/main.png', url: 'alhayat-takhtit/',
      available: true,
      description: 'كيف تنتقي خياراتك الحكيمة وسط عالم مليء بالضغوط والتوقعات المتضاربة — دليل عملي لاتخاذ قرارات أفضل وتصميم حياة تتوافق مع قيمك وأهدافك الحقيقية.',
    },
    {
      id: 77, title: 'الرجال من المريخ والنساء من الزهرة', titleEn: 'Men Are from Mars, Women Are from Venus',
      author: 'جون غراي', translator: null, year: 1992,
      category: 'العلاقات والحياة', price: 1100, image: 'men-mars-women-venus/main.png', url: 'men-mars-women-venus/',
      available: true,
      description: 'المرجع الأشهر في فهم الاختلافات النفسية بين الجنسين وكيف تؤثر على التواصل والعلاقات — مفتاح لبناء علاقات زوجية وعاطفية أكثر عمقاً وتفاهماً.',
    },
    {
      id: 78, title: 'كل لتعيش: برنامج التغذية الرائع الغني بالعناصر الغذائية لإنقاص الوزن بسرعة وثبات', titleEn: 'Eat to Live',
      author: 'جويل فورمان', translator: null, year: 2003,
      category: 'العلوم والمعرفة', price: 2500, image: 'eat-to-live/main.png', url: 'eat-to-live/',
      available: true,
      description: 'برنامج تغذوي علمي ثوري يُثبت أن الغذاء الصحيح الغني بالعناصر المغذية هو أفضل طريق لإنقاص الوزن والوقاية من الأمراض وعيش حياة أطول وأصح.',
    },
    {
      id: 79, title: 'الجانب الإيجابي من اللاعقلانية', titleEn: 'The Upside of Irrationality',
      author: 'دان آريلي', translator: null, year: 2010,
      category: 'علم النفس والمجتمع', price: 2900, image: 'upside-of-irrationality/main.png', url: 'upside-of-irrationality/',
      available: true,
      description: 'كيف تُفيدنا قراراتنا غير العقلانية في الواقع — الباحث الاقتصادي السلوكي دان آريلي يُثبت أن اللاعقلانية ليست دائماً خطأ بل قد تكون ميزة إنسانية فريدة.',
    },
    {
      id: 80, title: 'الإنسان ذلك المجهول', titleEn: 'Man the Unknown',
      author: 'ألكسيس كاريل', translator: 'عادل شفيق', year: 1935,
      category: 'الفلسفة والفكر', price: 2000, image: 'man-unknown/main.png', url: 'man-unknown/',
      available: true,
      description: 'دراسة فريدة ومعمّقة في طبيعة الإنسان من منظور علمي وفلسفي — يكشف ألكسيس كاريل الحائز على نوبل ما يجهله الإنسان عن نفسه ويدعو لإعادة اكتشاف الإنسانية.',
    },
    {
      id: 81, title: 'وتظن أنك نجوت', titleEn: null,
      author: 'إيناس سمير', translator: null, year: null,
      category: 'الروايات والأدب', price: 1400, image: 'wa-tazun-annaka-najawt/main.png', url: 'wa-tazun-annaka-najawt/',
      available: true,
      description: 'مجموعة نصوص وخواطر مترجمة بعناية تُعبّر عن ألم الفقدان والنجاة والأمل — قراءة تمسّ القلب وتُعبّر عمّا لا تجد له كلمات في لغتك الأم.',
    },
    {
      id: 82, title: 'كوتلر يتحدث عن التسويق: كيف تنشئ الأسواق وتغزوها وتسيطر عليها', titleEn: 'Kotler on Marketing',
      author: 'فيليب كوتلر', translator: 'فيصل عبد الله بابكر', year: 1999,
      category: 'الإدارة والأعمال', price: 990, image: 'kotler-marketing/main.png', url: 'kotler-marketing/',
      available: true,
      description: 'أبو التسويق الحديث يُقدّم رؤيته الشاملة لأسواق المستقبل — دليل استراتيجي لإنشاء الأسواق وغزوها والسيطرة عليها بأساليب تسويقية فعّالة ومبتكرة.',
    },
  ];
})();
