-- ================================================================
-- Derradj Shop — Admin-managed aggregate product rating fields
-- Run in: Supabase Dashboard → SQL Editor → New Query
--
-- WHAT: adds rating_value + rating_count to public.admin_products_catalog
-- — the single CRUD table for both books and electronics/subscriptions
-- (see derradj_shop_migrate_books_to_catalog.sql header comment). These
-- two columns are ADMIN-MANAGED AGGREGATE FIGURES only — a single
-- {ratingValue, ratingCount} pair per product row, surfaced via
-- Product.aggregateRating in the JSON-LD generated by
-- scripts/generate-product-pages.js. They are NOT derived from, and do
-- NOT replace, individual customer reviews — public.reviews and
-- public.customer_reviews remain the separate per-review testimonial
-- systems with real customer identities and are untouched here.
--
-- WHY: pages without any aggregateRating markup lose out on rich
-- results eligibility; a NULL rating on a freshly-added product would
-- also render a blank/invalid aggregateRating block if the page
-- generator assumed a value. This migration backfills every existing
-- active product with a deterministic rating and installs a trigger so
-- every future admin-added product (book or electronics) gets one too.
--
-- RLS: no new policies needed. admin_products_catalog RLS is row-level
-- only —
--   public_read_active_admin_products  FOR SELECT USING (is_active = true)
--   authenticated_manage_admin_products FOR ALL   USING/WITH CHECK (auth.role() = 'authenticated')
-- — neither policy inspects individual columns, so both already cover
-- rating_value/rating_count with zero changes (see
-- supabase-products-setup.sql section 5).
-- ================================================================

-- ── 1. Columns ──────────────────────────────────────────────────
ALTER TABLE public.admin_products_catalog
  ADD COLUMN IF NOT EXISTS rating_value NUMERIC(2,1),
  ADD COLUMN IF NOT EXISTS rating_count INTEGER;

ALTER TABLE public.admin_products_catalog
  DROP CONSTRAINT IF EXISTS chk_apc_rating_value;
ALTER TABLE public.admin_products_catalog
  ADD CONSTRAINT chk_apc_rating_value
  CHECK (rating_value IS NULL OR (rating_value >= 4.5 AND rating_value <= 4.9));
-- NUMERIC(2,1) only stores one decimal digit, so combined with this
-- range check the only values that can ever land in the column are
-- exactly {4.5, 4.6, 4.7, 4.8, 4.9} — never anything finer or outside it.

ALTER TABLE public.admin_products_catalog
  DROP CONSTRAINT IF EXISTS chk_apc_rating_count;
ALTER TABLE public.admin_products_catalog
  ADD CONSTRAINT chk_apc_rating_count
  CHECK (rating_count IS NULL OR rating_count > 0);

COMMENT ON COLUMN public.admin_products_catalog.rating_value IS
  'Admin-managed AGGREGATE rating (4.5–4.9), one figure per product row — feeds Product.aggregateRating.ratingValue in generated JSON-LD. NOT derived from public.reviews/customer_reviews individual review rows.';
COMMENT ON COLUMN public.admin_products_catalog.rating_count IS
  'Admin-managed AGGREGATE review count, one figure per product row — feeds Product.aggregateRating.reviewCount in generated JSON-LD. NOT a count of rows in public.reviews/customer_reviews.';

-- ── 2. Deterministic hash-derived rating helpers ───────────────────
-- Same formula is used by the one-off backfill (step 3) AND the
-- BEFORE INSERT trigger (step 4), so a given catalog_id always maps to
-- the same rating/count everywhere, forever (idempotent, reproducible,
-- not random() and not correlated with row/catalog_id ordering).
CREATE OR REPLACE FUNCTION public.compute_admin_product_rating_value(p_catalog_id INTEGER)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    -- ~65% of products land on 4.9 ("a significant portion")
    WHEN abs(hashtext(COALESCE(p_catalog_id, 0)::text || '::apc_rating_tier::v1')) % 100 < 65
      THEN 4.9::numeric
    -- the rest spread across {4.5,4.6,4.7,4.8} via an independent hash,
    -- so this split doesn't correlate with the 4.9/not-4.9 split above
    ELSE (ARRAY[4.5,4.6,4.7,4.8]::numeric[])[
           (abs(hashtext(COALESCE(p_catalog_id, 0)::text || '::apc_rating_subtier::v1')) % 4) + 1
         ]
  END;
$$;

CREATE OR REPLACE FUNCTION public.compute_admin_product_rating_count(p_catalog_id INTEGER)
RETURNS INTEGER
LANGUAGE sql
IMMUTABLE
AS $$
  -- 18–82 inclusive, independent salt from the rating_value hashes above
  SELECT 18 + (abs(hashtext(COALESCE(p_catalog_id, 0)::text || '::apc_rating_count::v1')) % 65);
$$;

-- ── 3. One-off backfill — active products only, only where NULL ────
-- Safe to re-run: rows that already have a rating_value are skipped,
-- and re-running against the same catalog_id always recomputes the
-- exact same value anyway (deterministic, not random()).
UPDATE public.admin_products_catalog
SET rating_value = public.compute_admin_product_rating_value(catalog_id),
    rating_count = public.compute_admin_product_rating_count(catalog_id)
WHERE rating_value IS NULL
  AND is_active = TRUE;

-- ── 4. BEFORE INSERT trigger — future products get a rating too ────
-- INSERT only, deliberately, modeled after reviews_fill_display_name()
-- in supabase-reviews.sql but WITHOUT the "OR UPDATE" clause: an admin
-- manually editing rating_value/rating_count on an existing product in
-- the edit form must have that stick and never get silently
-- overwritten on a later save.
CREATE OR REPLACE FUNCTION public.apc_fill_rating_defaults()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.rating_value IS NULL THEN
    NEW.rating_value := public.compute_admin_product_rating_value(NEW.catalog_id);
  END IF;
  IF NEW.rating_count IS NULL THEN
    NEW.rating_count := public.compute_admin_product_rating_count(NEW.catalog_id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_apc_fill_rating_defaults ON public.admin_products_catalog;
CREATE TRIGGER trg_apc_fill_rating_defaults
  BEFORE INSERT ON public.admin_products_catalog
  FOR EACH ROW EXECUTE FUNCTION public.apc_fill_rating_defaults();

-- ── 5. Reload PostgREST's schema cache (new columns above) ─────────
NOTIFY pgrst, 'reload schema';

-- ── Verify ──────────────────────────────────────────────────────
-- SELECT catalog_id, product_name, category, rating_value, rating_count
-- FROM public.admin_products_catalog
-- ORDER BY category, catalog_id;
--
-- SELECT rating_value, COUNT(*) AS n
-- FROM public.admin_products_catalog
-- WHERE is_active = TRUE
-- GROUP BY rating_value
-- ORDER BY rating_value;
-- ↑ expect only {4.5,4.6,4.7,4.8,4.9}, with 4.9 holding roughly 65% of rows
